services:
  - type: web
    name: boutique
    env: php
    plan: starter
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "sh scripts/deploy.sh && php artisan serve --host 0.0.0.0 --port $PORT"
